### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=WebStorm


###cat
GET http://localhost:5000/



### all users
GET http://localhost:5000/users/all
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ODRiYmI0MjU0Y2JkZDI3Zjg3Y2E1YyIsImlhdCI6MTczNjc1MjA1MiwiZXhwIjoxNzM2Nzk1MjUyfQ._LZ-cKR-h2t3OAuPCLWIxXJPAGADb-NHMtTcKx6CoRY

### nowy user
POST http://localhost:5000/users/register
Content-Type: application/json

 {
     "name":"firsewrww",
     "email":"2wwqqddddjbjdqqqq@2.com",
     "password":"qqqqq",
     "login":"qqqqq"
 }
### auth user
POST http://localhost:5000/auth/login
Content-Type: application/json

{
  "password":"qqqqq",
  "login":"qqqqq"
}
### get user info
GET http://localhost:5000/users/6784c68bbafd0382c8fa5914/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ODRjNjhiYmFmZDAzODJjOGZhNTkxNCIsImlhdCI6MTczNjc1NTc0OCwiZXhwIjoxNzM2Nzk4OTQ4fQ.lQM1SEX3dJbU1kalmrPaU4dc2xm_pQdcrhmHJVIKMLM

### edit user info
PUT http://localhost:5000/users/6784c68bbafd0382c8fa5914/profile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ODRjNjhiYmFmZDAzODJjOGZhNTkxNCIsImlhdCI6MTczNjc1NTc0OCwiZXhwIjoxNzM2Nzk4OTQ4fQ.lQM1SEX3dJbU1kalmrPaU4dc2xm_pQdcrhmHJVIKMLM

{
  "name": "firqw",
  "password": "dqwertyfdgdfg",
  "wiek": 17
}
### dodaj do friendow
POST http://localhost:5000/users/6784c68bbafd0382c8fa5914/friends
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ODRjNjhiYmFmZDAzODJjOGZhNTkxNCIsImlhdCI6MTczNjc1NTc0OCwiZXhwIjoxNzM2Nzk4OTQ4fQ.lQM1SEX3dJbU1kalmrPaU4dc2xm_pQdcrhmHJVIKMLM

{
  "login":"qqdddddd"
}
### dodaj do friendow
POST http://localhost:5000/users/676eaeb2b1a2489919992381/friends
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ODRjNjhiYmFmZDAzODJjOGZhNTkxNCIsImlhdCI6MTczNjc1NTc0OCwiZXhwIjoxNzM2Nzk4OTQ4fQ.lQM1SEX3dJbU1kalmrPaU4dc2xm_pQdcrhmHJVIKMLM

{
  "login":"qpie"
}
###otrzymaj moich frendow
GET http://localhost:5000/users/6784c68bbafd0382c8fa5914/friends
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ODRjNjhiYmFmZDAzODJjOGZhNTkxNCIsImlhdCI6MTczNjc1NTc0OCwiZXhwIjoxNzM2Nzk4OTQ4fQ.lQM1SEX3dJbU1kalmrPaU4dc2xm_pQdcrhmHJVIKMLM

### usun z frendow
DELETE http://localhost:5000/users/6784c68bbafd0382c8fa5914/friends
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ODRjNjhiYmFmZDAzODJjOGZhNTkxNCIsImlhdCI6MTczNjc1NTc0OCwiZXhwIjoxNzM2Nzk4OTQ4fQ.lQM1SEX3dJbU1kalmrPaU4dc2xm_pQdcrhmHJVIKMLM

{
  "login":"qqdddddd"
}
### add post
POST http://localhost:5000/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ODRjNjhiYmFmZDAzODJjOGZhNTkxNCIsImlhdCI6MTczNjc1NTc0OCwiZXhwIjoxNzM2Nzk4OTQ4fQ.lQM1SEX3dJbU1kalmrPaU4dc2xm_pQdcrhmHJVIKMLM

{

  "header": "asd",
  "text": "asfasfafasdas",
  "share": "All"
}
###edit post
PUT http://localhost:5000/posts/6784da289916ede7619c327a
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ODRjNjhiYmFmZDAzODJjOGZhNTkxNCIsImlhdCI6MTczNjc1NTc0OCwiZXhwIjoxNzM2Nzk4OTQ4fQ.lQM1SEX3dJbU1kalmrPaU4dc2xm_pQdcrhmHJVIKMLM

{
  "header": "ass",
  "text": "ass",
  "share": "None"
}

###delete post
DELETE http://localhost:5000/posts/6784da289916ede7619c327a
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ODRjNjhiYmFmZDAzODJjOGZhNTkxNCIsImlhdCI6MTczNjc1NTc0OCwiZXhwIjoxNzM2Nzk4OTQ4fQ.lQM1SEX3dJbU1kalmrPaU4dc2xm_pQdcrhmHJVIKMLM

###
PUT http://localhost:5000/posts/6784da079916ede7619c3275/likes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ODRjNjhiYmFmZDAzODJjOGZhNTkxNCIsImlhdCI6MTczNjc1NTc0OCwiZXhwIjoxNzM2Nzk4OTQ4fQ.lQM1SEX3dJbU1kalmrPaU4dc2xm_pQdcrhmHJVIKMLM

{
  "tryToLike":"676eaaa87843d4da883e8274"
}
### edit share w poste
PUT http://localhost:5000/posts/6784da079916ede7619c3275/share
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ODRjNjhiYmFmZDAzODJjOGZhNTkxNCIsImlhdCI6MTczNjc1NTc0OCwiZXhwIjoxNzM2Nzk4OTQ4fQ.lQM1SEX3dJbU1kalmrPaU4dc2xm_pQdcrhmHJVIKMLM

{
  "share":"All"
}
###add comment
POST http://localhost:5000/posts/6784da079916ede7619c3275/comments
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ODRjNjhiYmFmZDAzODJjOGZhNTkxNCIsImlhdCI6MTczNjc1NTc0OCwiZXhwIjoxNzM2Nzk4OTQ4fQ.lQM1SEX3dJbU1kalmrPaU4dc2xm_pQdcrhmHJVIKMLM

{
  "tagged": "6773ebf8308ea9d4dc4c6292",
  "text": "werre",
  "user": "676eaaa87843d4da883e8274"
}
###delete comment
DELETE http://localhost:5000/posts/6784dce2f50798f1ef1286ac/comments
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ODRjNjhiYmFmZDAzODJjOGZhNTkxNCIsImlhdCI6MTczNjc1NTc0OCwiZXhwIjoxNzM2Nzk4OTQ4fQ.lQM1SEX3dJbU1kalmrPaU4dc2xm_pQdcrhmHJVIKMLM

###eddit comment
PUT http://localhost:5000/posts/6784dba57eacd060aebb1175/comments
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ODRjNjhiYmFmZDAzODJjOGZhNTkxNCIsImlhdCI6MTczNjc1NTc0OCwiZXhwIjoxNzM2Nzk4OTQ4fQ.lQM1SEX3dJbU1kalmrPaU4dc2xm_pQdcrhmHJVIKMLM

{
  "text": "wedve"
}

###otrzymaj messages
GET http://localhost:5000/messages
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ODRjNjhiYmFmZDAzODJjOGZhNTkxNCIsImlhdCI6MTczNjc1NTc0OCwiZXhwIjoxNzM2Nzk4OTQ4fQ.lQM1SEX3dJbU1kalmrPaU4dc2xm_pQdcrhmHJVIKMLM

{
  "to": "676ea76eb19d3334d5b1073e"
}
###send messsage
POST http://localhost:5000/messages
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ODRjNjhiYmFmZDAzODJjOGZhNTkxNCIsImlhdCI6MTczNjc1NTc0OCwiZXhwIjoxNzM2Nzk4OTQ4fQ.lQM1SEX3dJbU1kalmrPaU4dc2xm_pQdcrhmHJVIKMLM

{
  "to": "676ea76eb19d3334d5b1073e",
  "text": "fdsfsdfssad"
}

###edit messsage
PATCH http://localhost:5000/messages/6784ddc8b9c5d500a4cf2b66
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ODRjNjhiYmFmZDAzODJjOGZhNTkxNCIsImlhdCI6MTczNjc1NTc0OCwiZXhwIjoxNzM2Nzk4OTQ4fQ.lQM1SEX3dJbU1kalmrPaU4dc2xm_pQdcrhmHJVIKMLM

{

  "text": "sad"
}
###delete messsage
DELETE http://localhost:5000/messages/6784ddc8b9c5d500a4cf2b66
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ODRjNjhiYmFmZDAzODJjOGZhNTkxNCIsImlhdCI6MTczNjc1NTc0OCwiZXhwIjoxNzM2Nzk4OTQ4fQ.lQM1SEX3dJbU1kalmrPaU4dc2xm_pQdcrhmHJVIKMLM
///asadasdasdasdadssadasdasdasd/asd/asd/asd/sa/dsadasd
###otrzymaj groupy
GET http://localhost:5000/groups
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ODJkYTQ0NjY3NWU4NjlhYThiNGQ1ZSIsImlhdCI6MTczNjYyODgwNCwiZXhwIjoxNzM2NjcyMDA0fQ.m42X340iUaQfwdDcRaE06cCU5E-abTaqFiqTBrHWzms

{
  "user": "676ea76eb19d3334d5b1073e"
}
###add group
POST http://localhost:5000/groups
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ODJkYTQ0NjY3NWU4NjlhYThiNGQ1ZSIsImlhdCI6MTczNjYyODgwNCwiZXhwIjoxNzM2NjcyMDA0fQ.m42X340iUaQfwdDcRaE06cCU5E-abTaqFiqTBrHWzms

{
  "name": "koty",
  "user": "676ea76eb19d3334d5b1073e"
}

###edit group
//"newUser"
PUT http://localhost:5000/groups/6773f9bc2872872122227881
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ODJkYTQ0NjY3NWU4NjlhYThiNGQ1ZSIsImlhdCI6MTczNjYyODgwNCwiZXhwIjoxNzM2NjcyMDA0fQ.m42X340iUaQfwdDcRaE06cCU5E-abTaqFiqTBrHWzms

{
  "name": "cat",
  "deleteUser": "676ea76eb19d3334d5b1073e"

}

###delete group
DELETE http://localhost:5000/groups/6773f9c52872872122227885
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ODJkYTQ0NjY3NWU4NjlhYThiNGQ1ZSIsImlhdCI6MTczNjYyODgwNCwiZXhwIjoxNzM2NjcyMDA0fQ.m42X340iUaQfwdDcRaE06cCU5E-abTaqFiqTBrHWzms
